#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER kat_app WITH ENCRYPTED PASSWORD '${KAT_APP_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO kat_app;
    GRANT USAGE ON SCHEMA public TO kat_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kat_app;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public
        GRANT USAGE, SELECT ON SEQUENCES TO kat_app;
EOSQL
